application: gdgnd-site
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /pages/(.*)
  static_files: pages/\1
  upload: pages/.*

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /bower_components/(.*)
  static_files: bower_components/\1
  upload: bower_components/.*

- url: /service/(.*)
  static_files: service/\1
  upload: service/.*

- url: /api/(.*)
  static_files: api/\1
  upload: api/.*

- url: /images/(.*)
  static_files: images/\1
  upload: images/.*

skip_files:
- ^(.*/)?node_modules/.*